#!/usr/bin/php
<?php
	chdir(__DIR__);
	error_reporting(E_ALL & ~E_NOTICE);

	require "../libraries/banshee/protocol/http.php";

	function get_copy($monsters, $monster) {
		if (isset($monster["_copy"]) == false) {
			return $monster;
		}

		$nam = strtolower($monster["_copy"]["name"]);
		$src = $monster["_copy"]["source"];

		$other = null;
		foreach($monsters[$src] as $mon) {
			if (strtolower($mon["name"]) == $nam) {
				$mon = get_copy($monsters, $mon);

				$monster["ac"] = $mon["ac"];
				$monster["hp"] = $mon["hp"];
				break;
			}
		}

		return $monster;
	}

	$website = new \Banshee\Protocol\HTTPS("5e.tools");
	$result = $website->GET("/data/bestiary/index.json");
	$sources = json_decode($result["body"], true);

	foreach ($sources as $idx => $source) {
		$result = $website->GET("/data/bestiary/".$source);
		$data = json_decode($result["body"], true);

		$monsters[$idx] = $data["monster"];
	}

	$list = array();
	foreach ($monsters as $section) {
		foreach ($section as $monster) {
			$name = trim($monster["name"], '"');
			$source = $monster["source"];
			$page = $monster["page"] ?? "?";

			$monster = get_copy($monsters, $monster);

			if (isset($monster["ac"]) == false) {
				$ac = "?";
			} else if (is_array($monster["ac"]) == false) {
				$ac = $monster["ac"];
			} else if (is_array($monster["ac"][0]) == false) {
				$ac = $monster["ac"][0];
			} else if (isset($monster["ac"][0]["ac"])) {
				$ac = $monster["ac"][0]["ac"];
			} else if (isset($monster["ac"]["special"])) {
				list($ac) = explode(" ", $monster["ac"]["special"]);
			} else {
				$ac = "?";
			}

			if (isset($monster["hp"]) == false) {
				$hp = "?";
			} else if (is_array($monster["hp"]) == false) {
				$hp = $monster["hp"];
			} else if (isset($monster["hp"]["average"])) {
				$hp = $monster["hp"]["average"];
			} else if (isset($monster["hp"]["special"])) {
				list($ac) = explode(" ", $monster["hp"]["special"]);
			} else {
				$hp = "?";
			}

			if (isset($monster["cr"]) == false) {
				$cr = "?";
			} else {
				$cr = $monster["cr"];
			}

			if (is_array($cr)) {
				$cr = $cr["cr"];
			}

			$size = ($monster["size"][0] ?? "M");

			$monster = sprintf("%s:%s:%s:%s:%s:%s:%s", $name, $cr, $ac, $hp, $size, $source, $page);
			array_push($list, $monster);
		}
	}

	$list = array_unique($list);
	sort($list);

	$max = count($list) - 1;

	$monsters = array();
	foreach ($list as $i => $monster) {
		$monster = str_replace("\"", "\\\"", $monster);
		list($name, $cr, $ac, $hp, $size, $source, $page) = explode(":", $monster);

		array_push($monsters, array(
			"name"   => $name,
			"cr"     => $cr,
			"hp"     => $hp,
			"ac"     => $ac,
			"size"   => $size,
			"source" => $source,
			"page"   => $page));
	}

	if (($fp = fopen("../public/data/monsters", "w")) == false) {
		return false;
	}

	fputs($fp, "<data>\n");
	fputs($fp, json_encode($monsters)."\n");
	fputs($fp, "</data>");

	fclose($fp);
?>
