#!/usr/bin/php
<?php
	require "getid3.php";

	$getID3 = new getID3;
	#$info = $getID3->analyze(__DIR__."/../../public/files/default_maps/river_crossing_1280x720-40.mp4");
	$info = $getID3->analyze(__DIR__."/../../public/resources/YCWQdwazZU8eZaDUtOY2V5bGpTLWRcEd/maps/Wizards_Tower.webm");

	print_r($info);
?>
